### ISSUE TITLE
API: task status should be a text constant

### ISSUE THREAD

**Issue by Kernald** [getting-things-gnome/GTGOnline#10]
Currently, when retrieving the tasks, the status is given this way:

> status (integer) = ['0' or '1' or '2']: Status of the Task

0, 1 or 2 should be replaced by text values (I guess they are "new", "dismissed", …), which would be:
- more clear
- more update-proof: what about introducing a new state, semantically between 0 and 1? Should it be named 3, or 1 and rename 1 and 2?

**Comment by parinporecha** [comment]
@Kernald , I chose such values initially to avoid spelling mistakes in text. GTG uses 'dismiss' for dismissed tasks. This had caused a lot of problems because the parser could not identify 'dismissed' coming from the sync.

Yes, text is more clear and update-proof but due to the parsing errors, I stuck with integers because the chances of a developer making mistakes with 0,1 and 2 is very less compared to the word strings

I could not understand the "introducing a new state" part. If you give a state other than the listed, then it won't cause any problems. Please can you explain it more ?

**Comment by Kernald** [comment]
> I could not understand the "introducing a new state" part. If you give a state other than the listed, then it won't cause any problems. Please can you explain it more ?

Let's say 0 is "todo" and 1 is "done" (I don't know the actual meanings), and you want to introduce an "in progress" state. You have two possibilities:
- Number it 3, but it's illogical, it comes before "done", so should be before 1
- Number it 1, move "done" to 2, and "dismissed" to 3. But it would break everything.

However, this part is not really an issue as it's really not likely to happen. I just think using text-constant would have been more clear, but if that's causing issues with the parser, don't worry :-)

**Comment by Kernald** [comment]
Maybe this issue should be closed?
