### ISSUE TITLE
API: register a new account

### ISSUE THREAD

**Issue by Kernald** [getting-things-gnome/GTGOnline#8]
Add a method to create a new account directly from the API, allowing any app to create an account without redirecting the user to the website.

**Comment by parinporecha** [comment]
@Kernald : Currently when a user tries to register on GTGOnline, we check if he has a gravatar profile or not (So as to avoid asking his first and last name). I think adding such method to the API (checking for gravatar, if not found, respond with an error message asking for name. Because we can't allow blank names) will complicate things on the app-side ( Please correct me if I am wrong ).
So, I'm thinking of a simplified version of registration method in which the app will have to compulsorily ask the first and last name of the user irrespective whether he has gravatar profile or not.
So, in this method - email, password, first name, last name will be mandatory fields
Is it okay ?

**Comment by Kernald** [comment]
Waiting for the answer from Gravatar will obviously be weird for the user (not really complicated to implement, but weird for the user). Asking for a first name and last name would be better, I think.

**Comment by parinporecha** [comment]
Method 'register' added to the API in commit f6747f2f7fdeceb1a324c717c6b9a17ddd14ef22
Please see the [updated](http://gtgonline-parinporecha.rhcloud.com/api/api_docs/) docs
Closing this issue

**Comment by Kernald** [comment]
I still have two remarks on this one:
- Should be `POST`, as you're creating a new resource and not specifying the access URL (the URL is always the same, it's the method URL, not the future resource one - see [here](http://stackoverflow.com/a/630475/775894) for a detailed explanation)
- If the registration is successful (so we got a 200 back), it would be nice to have an auth token as return value, once the auth token is implemented.

**Comment by parinporecha** [comment]
You were right. I've changed the method to POST :-)
I'll change the response body to the auth token when it is implemented

**Comment by Kernald** [comment]
Great! it begins to look good :-)
